// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnPyfjSD0IG7Niaf0e_E6VELO_C2V7WM4',
    appId: '1:682483977927:web:d3747c5393479f4d99b8e2',
    messagingSenderId: '682483977927',
    projectId: 'joumaafinal',
    authDomain: 'joumaafinal.firebaseapp.com',
    storageBucket: 'joumaafinal.appspot.com',
    measurementId: 'G-6FTHSHM848',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU1dN77kyI_VvDezrXjjs-NkQD40U300A',
    appId: '1:682483977927:android:4783bde783280eb099b8e2',
    messagingSenderId: '682483977927',
    projectId: 'joumaafinal',
    storageBucket: 'joumaafinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZFkr1M7p-Dd6vNB_G9MndnlsXwm9DMr4',
    appId: '1:682483977927:ios:b733d8c0e0d527a199b8e2',
    messagingSenderId: '682483977927',
    projectId: 'joumaafinal',
    storageBucket: 'joumaafinal.appspot.com',
    iosClientId: '682483977927-2nhui63tdqgho7efn4i56e6c52u1trdu.apps.googleusercontent.com',
    iosBundleId: 'com.jumaaapp.jumaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZFkr1M7p-Dd6vNB_G9MndnlsXwm9DMr4',
    appId: '1:682483977927:ios:d7201f43e38e14c199b8e2',
    messagingSenderId: '682483977927',
    projectId: 'joumaafinal',
    storageBucket: 'joumaafinal.appspot.com',
    iosClientId: '682483977927-hktvemd2l6a56n9hubvmhjd9drm9t1pe.apps.googleusercontent.com',
    iosBundleId: 'com.jumaaapp.jumaa.RunnerTests',
  );
}
